# Generated by Django 4.1.2 on 2024-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTName', models.CharField(max_length=100, null=True)),
                ('LAstName', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('PAssword', models.CharField(max_length=100, null=True)),
                ('Repassword', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
