# Generated by Django 4.1.2 on 2024-10-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='FIRSTName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='LAstName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='PAssword',
            new_name='Password',
        ),
    ]
