# Generated by Django 4.1.2 on 2024-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0003_remove_person_lastname_remove_person_repassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Repassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
