# Generated by Django 4.1.2 on 2024-12-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0004_person_lastname_person_repassword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
